Hammox.defmock(Treehouse.MockBranch, for: Treehouse.Branch)
Hammox.defmock(Treehouse.MockLoopback, for: Treehouse.Loopback)
Hammox.defmock(Treehouse.MockMdns, for: Treehouse.Mdns)
Hammox.defmock(Treehouse.MockRegistry, for: Treehouse.Registry)
Hammox.defmock(Treehouse.MockSystem, for: Treehouse.System)
